
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import tkinter as tk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import subprocess

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\AiProject\windows\Window1\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def close_gui():
    """This function closes the Tkinter GUI."""
    window.destroy()

def run_another_script():
    script_path = "main.py"  
    try:
        subprocess.run(["python", script_path], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error: {e}")


window = Tk()

window.geometry("700x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    70.0,
    fill="#4EB5C8",
    outline="")

canvas.create_text(
    200.0,
    13.0,
    anchor="nw",
    text="Gumball Maze ",
    fill="#FFFFFF",
    font=("Itim Regular", 40 * -1)
)

canvas.create_rectangle(
    0.0,
    69.0,
    350.0,
    550.0,
    fill="#92D5DD",
    outline="")

canvas.create_text(
    25.0,
    94.0,
    anchor="nw",
    text="Team Members",
    fill="#000000",
    font=("Itim Regular", 40 * -1)
)

canvas.create_text(
    8.0,
    174.0,
    anchor="nw",
    text="1- Mohamed Sarary  \n2- Mohamed Awadin \n3- Yousef Elshabrawy \n4- Mohamed Fahmy \n5- Hany Elesawy\n6- Mahmoud Labib\n7- Mohamed Alkoka \n8- Abdelrahman Ehab \n9- Mohamed Zahran \n10 - Mohamed Allam ",
    fill="#000000",
    font=("Itim Regular", 20 * -1)
)

canvas.create_text(
    25.0,
    432.0,
    anchor="nw",
    text="Powered by :  ",
    fill="#000000",
    font=("Itim Regular", 32 * -1)
)

canvas.create_text(
    10.0,
    480.0,
    anchor="nw",
    text="Prof.Assc: Amira Yassin\nEng : Fatma Gamal ",
    fill="#000000",
    font=("Itim Regular", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=run_another_script,
    relief="flat"
)
button_1.place(
    x=547.0,
    y=125.0,
    width=106.0,
    height=99.0
)


button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=close_gui,
    relief="flat"
)
button_2.place(
    x=396.0,
    y=123.0,
    width=106.0,
    height=99.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    601.0,
    419.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
